defaults:
  - _self_
  - characters: default
  - system_prompts: default

llm_config:
  cache_seed: null
  temperature: 0
  timeout: 120
  config_list_path: "conf/OAI_CONFIG_LIST.txt"
  filter_dict:
    model: ["gemini-1.5-pro"]

podcast_config:
  topic: "Democracy"
  n_rounds: 10
  character_cfg:
    hosts: ${characters.hosts}  # Reference to host in characters.yaml
    guests: ${characters.guests}  # Reference to guests in characters.yaml
  length: 10
  
system_prompts: ${system_prompts}  # Reference to system_prompts.yaml
